global:
  scrape_interval: 5s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
    scheme: "http"
    metrics_path: "/metrics"

  - job_name: 'skinet'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:5000']
    scheme: "http"
    metrics_path: "/metrics"    

